22 Migrate Color Wheel Activity #22
codewithher/CC-Lantern pull request #24
Opened 2024-04-02 17:45 UTC by innaamogolonova

**Why:**

Closes the following issues (all PRs must close an issue):

- closes #22 

**What's being changed**

Simplifies the rainbow() method in act3 examples to implement Lantern.h library, making the function easier to read. 

**Testing instructions**

The easiest way to test is to run the rainbow method in activity 3 which double as testing files. 

You can verify that the code works appropriately by visually inspecting the colors that result from the activity function calls.

- [ ] The LED goes through the complete color spectrum (red to green to blue back to red)
- [ ] The color change is gradual and smooth 
- [ ] The rainbow lasts the specified "seconds" amount of time
- [ ] Change the number of seconds and make sure the rainbow lasts appropriate amount of time 

**Check off the following**

- [ ] I have assigned @totally-not-frito-lays as a reviewer

2024-04-02 22:00 UTC, totally-not-frito-lays requested changes
Just asking for a bit more clarity. The code works well as is really enjoyable to watch.

Something interesting I noted is that when giving invalid input (ie. negative numbers) such as `rainbow(-5)` the behavior here is different than from `CC-Library-Lantern`. In `CC-Library-Lantern` the behavior was rapidly changing colors. In `CC-Lantern` (this repo), the behavior runs slowly, starting at orange.

This may be a quirk of our implementation of the `wait()` wrapper function. I'll open up a ticket for this.

2024-04-02 22:12 UTC, totally-not-frito-lays commented
> Just asking for a bit more clarity. The code works well as is really enjoyable to watch.
> 
> Something interesting I noted is that when giving invalid input (ie. negative numbers) such as `rainbow(-5)` the behavior here is different than from `CC-Library-Lantern`. In `CC-Library-Lantern` the behavior was rapidly changing colors. In `CC-Lantern` (this repo), the behavior runs slowly, starting at orange.
> 
> This may be a quirk of our implementation of the `wait()` wrapper function. I'll open up a ticket for this.

Opened ticket #25 for this. Bounds handling inside this function is the easiest way to resolve this for now but it may be worth some exploration to see if this occurs for other functions.

Just to clarify, this PR does not need to resolve #25.

2024-05-08 19:17 UTC, innaamogolonova commented
Addressed the changes requested by: 
- commenting out other functions
- adding a bounds check
- adding an explanation for 765 number (both in code and on notion)

2024-05-24 00:34 UTC, totally-not-frito-lays commented on examples/act3-functions/act3-functions.ino
> +    lantern.setColor(seconds / 765, lantern.color(Red, Green, Blue));
@innaamogolonova I think we can communicate some of what the comment is saying into code.

ie.
```ino
const int steps = 255;  // Number of steps for the gradient
const int num_led = 3;  // Number of colors (RGB)
const int total_steps = steps * num_led;  // Total steps in the gradient
const float time_per_color = seconds / total_steps;  // Time for each color step

for (int Red = 255; Red > 0; Red--) {
    Green += 1;
    lantern.setColor(time_per_color, lantern.color(Red, Green, Blue));
}

2024-05-24 00:43 UTC, totally-not-frito-lays approved these changes
Approving this PR! I just made the code a little more readable in the example :)

2024-06-23 16:41 UTC, merged